export const FETCH_COINS = "FETCH_COINS";
export const SET_TOTALS = "SET_TOTALS";
export const TOGGLE_BTC = "TOGGLE_BTC";
export const FETCH_COIN_DETAILS = "FETCH_COIN_DETAILS";
export const FETCH_COIN_CHART = "FETCH_COIN_CHART";
export const FETCH_COIN_HOLDINGS = "FETCH_COIN_HOLDINGS";
export const ADD_COIN = "ADD_COIN";
export const CLEAR_SELECTED_COIN = "CLEAR_SELECTED_COIN";
